import { useState } from 'react'
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom'
import HistoryPanel from './components/HistoryPanel.jsx'
import ResponseOutput from './components/ResponseOutput.jsx'
import ThemeToggle from './components/ThemeToggle.jsx'
import MicButton from './components/MicButton.jsx'
import './App.css'

function Home() {
  const [queryText, setQueryText] = useState('')
  const [response, setResponse] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [isVoiceActive, setIsVoiceActive] = useState(false)

  // Retrieve or generate a stable session ID so that query history shows up in the history panel
  const [sessionId] = useState(() => {
    const key = 'devwhisper_session_id'
    const existing = sessionStorage.getItem(key)
    if (existing) return existing
    const newId = 'web-' + Math.random().toString(36).substring(2, 9)
    sessionStorage.setItem(key, newId)
    return newId
  })

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!queryText.trim() || loading) return

    setLoading(true)
    setError(null)
    setResponse('')

    // Payload matches the tool-calls structure expected by main.py webhook handler
    const payload = {
      message: {
        type: 'tool-calls',
        sessionId: sessionId,
        toolCalls: [
          {
            id: crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2),
            type: 'function',
            function: {
              name: 'query_codebase',
              arguments: JSON.stringify({ query: queryText })
            }
          }
        ]
      }
    }

    try {
      const res = await fetch('/webhook', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(payload)
      })

      if (!res.ok) {
        throw new Error(`Server returned HTTP ${res.status}`)
      }

      const data = await res.json()
      if (data.status === 'error') {
        throw new Error(data.message || 'Error executing codebase query.')
      }

      const resultText = data.results?.[0]?.result
      if (resultText) {
        setResponse(resultText)
        setQueryText('')
      } else {
        setResponse('No response was generated by the codebase assistant.')
      }
    } catch (err) {
      setError(err.message || 'Failed to reach the DevWhisper backend.')
    } finally {
      setLoading(false)
    }
  }

  const toggleVoiceMode = () => {
    setIsVoiceActive(prev => !prev)
  }

  return (
    <div className="landing-container">
      <header className="hero-header">
        <h1 className="logo-text">DevWhisper</h1>
        <p className="subtitle-text">Voice-native developer experience agent</p>
      </header>

      <main className="interactive-card">
        {/* Voice Segment */}
        <section className="voice-section">
          <MicButton />
          <div className="voice-status">
            <p className="voice-status-title">Voice Assistant</p>
            <p className="voice-status-desc">
              Voice flow is ready. Click the mic button to start/stop recording.
            </p>
          </div>
        </section>

        <div className="or-divider">
          <span className="line"></span>
          <span className="divider-text">OR QUERY VIA TEXT</span>
          <span className="line"></span>
        </div>

        {/* Text Input Segment */}
        <section className="text-query-section">
          <form onSubmit={handleSubmit} className="query-form">
            <div className="textarea-wrapper">
              <textarea
                value={queryText}
                onChange={e => setQueryText(e.target.value)}
                placeholder="Ask about your codebase... (e.g. In main.py, what functions are found?)"
                disabled={loading}
                rows={3}
                className="query-input"
              />
            </div>
            <button 
              type="submit" 
              disabled={loading || !queryText.trim()} 
              className="submit-button"
            >
              {loading ? 'Analyzing...' : 'Send Query'}
            </button>
          </form>
        </section>

        {/* Response Rendering */}
        <ResponseOutput response={response} loading={loading} error={error} />
      </main>

      <footer className="landing-footer">
        <p className="session-info">
          Active Session ID: <code>{sessionId}</code>
        </p>
        <Link to="/history" className="history-link">
          📋 View Full Session History &rarr;
        </Link>
      </footer>
    </div>
  )
}

function App() {
  return (
    <BrowserRouter>
      <div className="app">
        <ThemeToggle />

        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/history" element={<HistoryPanel />} />
        </Routes>
      </div>
    </BrowserRouter>
  );
}

export default App