name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Thanks for your first PR to DevWhisper! 🎉 A maintainer will review it soon. Make sure your PR is linked to an issue and includes the ECSoC26 label before merging.'
        issue-message: 'Thanks for opening your first issue on DevWhisper! 👋 We''ll take a look and get back to you soon. If you''d like to work on it yourself, drop a comment and we''ll assign it to you.'
